version: '2'
services:
  admin-ui.c2s.com:
    image: bhits/admin-portal-ui:0.9.0
    volumes:
      - /c/Users/java:/java
    mem_limit: 1000m
    links:
      - discovery-server.c2s.com
    restart: always

  clamd.c2s.com:
    image: dinkel/clamavd

  context-handler.c2s.com:
    image: bhits/context-handler:1.3.0
    volumes:
      - /c/Users/java:/java
    mem_limit: 1000m
    links:
      - discovery-server.c2s.com
      - pcm-db.c2s.com
    environment:
      spring.config.location: "file:/java/C2S_PROPS/context-handler/"
    restart: always

  discovery-server.c2s.com:
    image: bhits/discovery-server:0.4.0
    environment:
      spring.config.location: "file:/java/C2S_PROPS/discovery-server/"
      TZ: "US/Eastern"
    volumes:
      - /c/Users/java:/java
    mem_limit: 1500m
    ports:
      - "8761:8761"
    restart: always

  document-validator-r1.c2s.com:
    image: bhits/document-validator-r1:0.5.0
    volumes:
      - /c/Users/java:/java
    ports:
      - "8461:8443"
      - "8460:8080"
    restart: always

  document-validator-ccda-r2.c2s.com:
    image: bhits/document-validator-ccda-r2:0.5.0
    mem_limit: 1500m
    volumes:
      - /c/Users/java:/java
    ports:
      - "8462:8443"
      - "8463:8080"
    restart: always

  dss.c2s.com:
    image: bhits/dss:1.9.0
    volumes:
      - /c/Users/java:/java
    mem_limit: 1500m
    environment:
      spring.config.location: "file:/java/C2S_PROPS/dss/"
    links:
      - discovery-server.c2s.com
      - guvnor.c2s.com
      - document-validator.c2s.com
    restart: always

  edge-server.c2s.com:
    image: bhits/edge-server:0.7.0
    volumes:
      - /c/Users/java:/java
    mem_limit: 1500m
    environment:
      spring.config.location: "file:/java/C2S_PROPS/edge-server/"
    ports:
      - "80:80"
      - "443:443"
    links:
      - discovery-server.c2s.com
      - pls.c2s.com
      - openempi.c2s.com
      - guvnor.c2s.com
      - uaa.c2s.com
      - document-validator.c2s.com
      - document-validator-r1.c2s.com
    restart: always

  guvnor.c2s.com:
    image: bhits/guvnor:5.5.0
    volumes:
      - /c/Users/java:/java
    ports:
      - "8457:8443"
    restart: always

  iexhub.c2s.com:
    image: bhits/iexhub-fork:0.2.0
    ports:
      - "8000:8000"
    environment:
      CATALINA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000
    mem_limit: 4000m
    volumes:
      - /c/Users/java:/java
      - /c/Users/java/C2S_PROPS/iexhub/test:/usr/local/tomcat/bin/test
      - /c/Users/java/C2S_PROPS/iexhub/temp:/temp
      - /c/Users/java/C2S_PROPS/iexhub/temp/output:/temp/output
      - /c/Users/java/C2S_LOGS/iexhub/test:/usr/local/tomcat/test
      - /c/Users/java/C2S_LOGS/iexhub/results:/results
      - /c/Users/java/C2S_LOGS/iexhub/results/DebugLogs:/results/DebugLogs
    links:
      - openempi.c2s.com
    restart: always

  patient-registration.c2s.com:
    image: bhits/patient-registration:1.10.0
    volumes:
      - /c/Users/java:/java
    mem_limit: 1500m
    links:
      - discovery-server.c2s.com
      - uaa.c2s.com
      - iexhub.c2s.com
    restart: always

  patient-user-db.c2s.com:
    image: mysql:5.7
    volumes_from:
      - patient-user-data.c2s.com
    environment:
        MYSQL_ROOT_PASSWORD: ${PATIENT_USER_DB_PASSWORD}
        MYSQL_DATABASE: patient-user
    ports:
      - "3310:3306"
    restart: always

  patient-user-data.c2s.com:
    image: busybox
    volumes:
      - /c/Users/java/mysql/patient-user:/var/lib/mysql

  patient-user.c2s.com:
    image: bhits/patient-user:0.8.0
    volumes:
      - /c/Users/java:/java
    mem_limit: 1000m
    environment:
      spring.config.location: "file:/java/C2S_PROPS/patient-user/"
    ports:
      - "8452:8452"
    links:
      - discovery-server.c2s.com
      - patient-user-db.c2s.com
      - uaa.c2s.com
    restart: always

  pcm.c2s.com:
    image: bhits/pcm:1.14.0
    volumes:
      - /c/Users/java:/java
    environment:
      spring.config.location: "file:/java/C2S_PROPS/pcm/"
      TZ: "US/Eastern"
    mem_limit: 1500m
    links:
      - uaa.c2s.com
      - pcm-db.c2s.com
      - pls.c2s.com
      - discovery-server.c2s.com
      - clamd.c2s.com
    restart: always
  pcm-db.c2s.com:
    image: mysql:5.7
    volumes_from:
      - pcm-db-data.c2s.com
    environment:
        MYSQL_ROOT_PASSWORD: ${PCM_DB_PASSWORD}
        MYSQL_DATABASE: pcm
    ports:
      - "3307:3306"
    restart: always
  pcm-db-data.c2s.com:
    image: busybox
    volumes:
      - /c/Users/java/mysql/pcm:/var/lib/mysql

  pep.c2s.com:
    image: bhits/pep:1.3.0
    volumes:
      - /c/Users/java:/java
    mem_limit: 1000m
    links:
      - discovery-server.c2s.com
    environment:
      spring.config.location: "file:/java/C2S_PROPS/pep/"
    restart: always

  phr.c2s.com:
    image: bhits/phr:1.14.0
    volumes:
      - /c/Users/java:/java
    environment:
      spring.config.location: "file:/java/C2S_PROPS/phr/"
      logging.level.org.springframework.security: "debug"
    mem_limit: 1500m
    links:
      - phr-db.c2s.com
      - redis.c2s.com
      - discovery-server.c2s.com
      - iexhub.c2s.com
    restart: always
  phr-db.c2s.com:
    image: mysql:5.7
    volumes_from:
      - phr-db-data.c2s.com
    environment:
        MYSQL_ROOT_PASSWORD: ${PHR_DB_PASSWORD}
        MYSQL_DATABASE: phr
    ports:
      - "3309:3306"
    restart: always
  phr-db-data.c2s.com:
    image: busybox
    volumes:
      - /c/Users/java/mysql/phr:/var/lib/mysql

  pls.c2s.com:
    image: bhits/pls:1.7.0
    volumes:
      - /c/Users/java:/java
    ports:
      - "8080:8080"
    links:
      - pls-db.c2s.com
    restart: always

  pls-db.c2s.com:
    image: mysql:5.7
    volumes_from:
      - pls-db-data.c2s.com
    volumes:
      - /c/Users/java/C2S_PROPS/pls:/docker-entrypoint-initdb.d
    mem_limit: 1000m
    environment:
        MYSQL_ROOT_PASSWORD: ${PLS_DB_PASSWORD}
        MYSQL_DATABASE: npi
    ports:
      - "3308:3306"
    restart: always

  pls-db-data.c2s.com:
    image: busybox
    volumes:
      - /c/Users/java/mysql/pls:/var/lib/mysql

  pp-ui.c2s.com:
    image: bhits/pp-ui:0.16.
    volumes:
      - /c/Users/java:/java
    mem_limit: 1000m
    links:
      - discovery-server.c2s.com
    restart: always

  redis.c2s.com:
    image: redis
    ports:
      - "6379:6379"
    restart: always

  try-policy.c2s.com:
    image: bhits/try-policy:1.9.0
    volumes:
      - /c/Users/java:/java
    mem_limit: 1000m
    links:
      - discovery-server.c2s.com
    restart: always

  uaa.c2s.com:
    image: bhits/uaa:3.4.1
    volumes:
      - /c/Users/java:/java
    ports:
      - "8443:8443"
    mem_limit: 1500m
    links:
      - uaa-db.c2s.com
    restart: always
  uaa-db.c2s.com:
    image: mysql:5.7
    volumes_from:
      - uaa-db-data.c2s.com
    environment:
        MYSQL_ROOT_PASSWORD: ${UAA_DB_PASSWORD}
        MYSQL_DATABASE: uaa
    ports:
      - "3306:3306"
    restart: always
  uaa-db-data.c2s.com:
    image: busybox
    volumes:
      - /c/Users/java/mysql/uaa:/var/lib/mysql