uaa.mhc.com:
  image: "bhits/uaa:3.4.1"
  volumes:
    - /usr/local/java:/java
  mem_limit: 1500m
  links:
    - uaa-db.mhc.com
uaa-db.mhc.com:
  image: mysql:5.7
  volumes_from:
    - uaa-db-data.mhc.com
  environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: uaa
uaa-db-data.mhc.com:
  image: busybox
  volumes:
    - /usr/local/java/mysql/uaa:/var/lib/mysql
pcm.mhc.com:
  image: "bhits/pcm:1.14.0-SNAPSHOT"
  volumes:
    - /usr/local/java:/java
  environment:
    spring.config.location: "file:/java/MHC_PROPS/pcm/"
    TZ: "US/Eastern"
  entrypoint: ["java","-Xms512m","-Xmx700m","-XX:PermSize=512m","-XX:MaxPermSize=128m","-Xss1m","-jar","/pcm.jar","--spring.profiles.active=docker"]
  mem_limit: 2000m
  links:
    - uaa.mhc.com
    - pcm-db.mhc.com
    - pls.mhc.com
    - discovery-server.mhc.com
    - clamd.mhc.com
pcm-db.mhc.com:
  image: mysql:5.7
  volumes_from:
    - pcm-db-data.mhc.com
  environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: pcm
pcm-db-data.mhc.com:
  image: busybox
  volumes:
    - /usr/local/java/mysql/pcm:/var/lib/mysql
pls.mhc.com:
  image: "bhits/pls:1.6.0"
  volumes:
    - /usr/local/java:/java
  links:
    - pls-db.mhc.com
pls-db.mhc.com:
  image: mysql:5.7
  volumes_from:
    - pls-db-data.mhc.com
  mem_limit: 1000m
  environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: npi
pls-db-data.mhc.com:
  image: busybox
  volumes:
    - /usr/local/java/mysql/pls:/var/lib/mysql
    - /usr/local/java/MHC_PROPS/pls/init-db:/docker-entrypoint-initdb.d
pp-ui.mhc.com:
  image: "bhits/pp-ui:0.14.0"
  volumes:
    - /usr/local/java:/java
  mem_limit: 1000m
  links:
    - discovery-server.mhc.com
admin-ui.mhc.com:
  image: "bhits/admin-portal-ui:0.7.0"
  volumes:
    - /usr/local/java:/java
  mem_limit: 1000m
  links:
    - discovery-server.mhc.com
dss.mhc.com:
  image: "bhits/dss:1.8.0-SNAPSHOT"
  volumes:
    - /usr/local/java:/java
  entrypoint: ["java","-Xms256m","-Xmx512m","-XX:PermSize=64m","-XX:MaxPermSize=128m","-Xss1m","-jar","/dss.jar","--spring.profiles.active=docker"]
  mem_limit: 1500m
  environment:
    spring.config.location: "file:/java/MHC_PROPS/dss/"
  links:
    - discovery-server.mhc.com
    - guvnor.mhc.com
    - document-validator.mhc.com
    - document-validator-r1.mhc.com
try-policy.mhc.com:
  image: "bhits/try-policy:1.8.0"
  volumes:
    - /usr/local/java:/java
  entrypoint: ["java","-Xms128m","-Xmx256m","-XX:PermSize=32m","-XX:MaxPermSize=64m","-Xss1m","-jar","/tryPolicy.jar","--spring.profiles.active=docker"]
  mem_limit: 1000m
  links:
    - discovery-server.mhc.com
phr.mhc.com:
  image: "bhits/phr:1.12.0"
  volumes:
    - /usr/local/java:/java
  environment:
    spring.config.location: "file:/java/MHC_PROPS/phr/"
    logging.level.org.springframework.security: "debug"
  entrypoint: ["java","-Xms256m","-Xmx512m","-XX:PermSize=64m","-XX:MaxPermSize=128m","-Xss1m","-jar","/phr.jar","--spring.profiles.active=docker"]
  mem_limit: 1500m
  links:
    - phr-db.mhc.com
    - redis.mhc.com
    - discovery-server.mhc.com
    - iexhub.mhc.com
phr-db.mhc.com:
  image: mysql:5.7
  volumes_from:
    - phr-db-data.mhc.com
  environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: phr
phr-db-data.mhc.com:
  image: busybox
  volumes:
    - /usr/local/java/mysql/phr:/var/lib/mysql
redis.mhc.com:
  image: redis
clamd.mhc.com:
  image: dinkel/clamavd
iexhub.mhc.com:
  image: "bhits/iexhub:0.3.0-SNAPSHOT"
  restart: always
  environment:
    CATALINA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000 -Dlog4j.configuration=file:/java/MHC_PROPS/iexhub/temp/log4j.properties
  mem_limit: 4000m
  volumes:
    - /usr/local/java:/java
    - /usr/local/java/MHC_PROPS/iexhub/test:/usr/local/tomcat/bin/test
    - /usr/local/java/MHC_PROPS/iexhub/temp:/temp
    - /usr/local/java/MHC_PROPS/iexhub/temp/output:/temp/output
    - /usr/local/java/MHC_LOGS/iexhub/results:/results
    - /usr/local/java/MHC_LOGS/iexhub/results/DebugLogs:/results/DebugLogs
patient-registration.mhc.com:
  image: "bhits/patient-registration:1.9.0"
  environment:
    spring.config.location: "file:/java/MHC_PROPS/patient-registration/"
  volumes:
    - /usr/local/java:/java
  entrypoint: ["java","-Xms256m","-Xmx512m","-XX:PermSize=64m","-XX:MaxPermSize=128m","-Xss1m","-jar","/patient-registration.jar","--spring.profiles.active=docker"]
  mem_limit: 1500m
  links:
    - discovery-server.mhc.com
    - uaa.mhc.com
    - iexhub.mhc.com
patient-user-db.mhc.com:
  image: mysql:5.7
  volumes_from:
    - patient-user-data.mhc.com
  environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: patient-user
patient-user-data.mhc.com:
  image: busybox
  volumes:
    - /usr/local/java/mysql/patient-user:/var/lib/mysql
patient-user.mhc.com:
  image: "bhits/patient-user:0.7.0"
  volumes:
    - /usr/local/java:/java
  entrypoint: ["java","-Xms256m","-Xmx512m","-XX:PermSize=64m","-XX:MaxPermSize=128m","-Xss1m","-jar","/patient-user.jar","--spring.profiles.active=mysql,docker"]
  mem_limit: 1000m
  environment:
    spring.config.location: "file:/java/MHC_PROPS/patient-user/"
  links:
    - discovery-server.mhc.com
    - patient-user-db.mhc.com
    - uaa.mhc.com
discovery-server.mhc.com:
  image: "bhits/discovery-server:0.3.0"
  volumes:
    - /usr/local/java:/java
  entrypoint: ["java","-Djavax.net.ssl.trustStore=/java/keystore/mhc.keystore","-Djavax.net.ssl.trustStorePassword=changeit","-Xms256m","-Xmx512m","-XX:PermSize=64m","-XX:MaxPermSize=128m","-Xss1m","-jar","/discovery-server.jar","--spring.profiles.active=ssl,docker"]
  mem_limit: 1500m
edge-server.mhc.com:
  image: "bhits/edge-server:0.5.0"
  volumes:
    - /usr/local/java:/java
  entrypoint: ["java","-Djavax.net.ssl.trustStore=/java/keystore/mhc.keystore","-Djavax.net.ssl.trustStorePassword=changeit","-Xms256m","-Xmx512m","-XX:PermSize=64m","-XX:MaxPermSize=128m","-Xss1m","-jar","/edge-server.jar","--spring.profiles.active=ssl,eureka-ssl,docker"]
  mem_limit: 1500m
  environment:
    spring.config.location: "file:/java/MHC_PROPS/edge-server/"
  ports:
    - "80:80"
    - "443:443"
  links:
    - discovery-server.mhc.com
    - pls.mhc.com
    - guvnor.mhc.com
    - uaa.mhc.com
    - document-validator.mhc.com
    - document-validator-r1.mhc.com
guvnor.mhc.com:
  image: bhits/mhc-guvnor:5.5.0
  volumes:
    - /usr/local/java:/java
document-validator.mhc.com:
  image: bhits/document-validator-ccda-r2:0.3.0
  volumes:
    - /usr/local/java:/java
document-validator-r1.mhc.com:
  image: bhits/document-validator-ccda-r1:0.3.0
  volumes:
    - /usr/local/java:/java
pep.mhc.com:
  image: bhits/pep:1.1.0
  volumes:
    - /usr/local/java:/java
  entrypoint: ["java","-Xms128m","-Xmx256m","-XX:PermSize=32m","-XX:MaxPermSize=64m","-Xss1m","-jar","/pep.jar","--spring.profiles.active=docker"]
  mem_limit: 1000m
  links:
    - discovery-server.mhc.com
  environment:
    spring.config.location: "file:/java/MHC_PROPS/pep/"
context-handler.mhc.com:
  image: bhits/context-handler:1.1.0
  volumes:
    - /usr/local/java:/java
  entrypoint: ["java","-Djavax.net.ssl.trustStore=/java/keystore/mhc.keystore","-Djavax.net.ssl.trustStorePassword=changeit","-Xms256m","-Xmx512m","-XX:PermSize=64m","-XX:MaxPermSize=128m","-Xss1m","-jar","/contextHandler.jar","--spring.profiles.active=docker"]
  mem_limit: 1000m
  links:
    - discovery-server.mhc.com
    - pcm-db.mhc.com
    - audit-service.mhc.com
  environment:
    spring.config.location: "file:/java/MHC_PROPS/context-handler/"
audit-service-db.mhc.com:
  image: mysql:5.7
  volumes_from:
    - audit-service-db-data.mhc.com
  environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: audit
audit-service-db-data.mhc.com:
  image: busybox
  volumes:
    - /usr/local/java/mysql/audit-service:/var/lib/mysql
    - /usr/local/java/MHC_PROPS/audit-service/init-db:/docker-entrypoint-initdb.d
audit-service.mhc.com:
  image: bhits/audit-service:0.5
  volumes:
    - /usr/local/java:/java
  links:
    - audit-service-db.mhc.com
