version: '2'
services:
  uaa.c2s.com:
    image: "bhits/uaa:3.1.0"
    volumes:
      - /c/Users/java:/java
    ports:
      - "8443:8443"
    mem_limit: 1500m
    links:
      - uaa-db.c2s.com
    restart: always
  uaa-db.c2s.com:
    image: mysql:5.7
    volumes_from:
      - uaa-db-data.c2s.com
    environment:
        MYSQL_ROOT_PASSWORD: admin
        MYSQL_DATABASE: uaa
    ports:
      - "3306:3306"
    restart: always
  uaa-db-data.c2s.com:
    image: busybox
    volumes:
      - /c/Users/java/mysql/uaa:/var/lib/mysql
  pcm.c2s.com:
    image: "bhits/pcm:1.11.0"
    volumes:
      - /c/Users/java:/java
    environment:
      spring.config.location: "file:/java/C2S_PROPS/pcm/"
      TZ: "US/Eastern"
    entrypoint: ["java","-Xms256m","-Xmx512m","-XX:PermSize=64m","-XX:MaxPermSize=128m","-Xss1m","-jar","/pcm.jar","--spring.profiles.active=docker"]
    mem_limit: 1500m
    links:
      - uaa.c2s.com
      - pcm-db.c2s.com
      - pls.c2s.com
      - discovery-server.c2s.com
      - clamd.c2s.com
    restart: always
  pcm-db.c2s.com:
    image: mysql:5.7
    volumes_from:
      - pcm-db-data.c2s.com
    environment:
        MYSQL_ROOT_PASSWORD: admin
        MYSQL_DATABASE: pcm
    ports:
      - "3307:3306"
    restart: always
  pcm-db-data.c2s.com:
    image: busybox
    volumes:
      - /c/Users/java/mysql/pcm:/var/lib/mysql
  pls.c2s.com:
    image: "bhits/pls:1.6.0"
    volumes:
      - /c/Users/java:/java
    ports:
      - "8453:8443"
      - "8080:8080"
    links:
      - pls-db.c2s.com
    restart: always
  pls-db.c2s.com:
    image: mysql:5.7
    volumes_from:
      - pls-db-data.c2s.com
    mem_limit: 1000m
    environment:
        MYSQL_ROOT_PASSWORD: admin
        MYSQL_DATABASE: npi
    ports:
      - "3308:3306"
    volumes:
      - /c/Users/java/C2S_PROPS/pls:/usr/local/pls
      - /c/Users/java/C2S_PROPS/pls/sql:/usr/local/pls/sql
    restart: always
  pls-db-data.c2s.com:
    image: busybox
    volumes:
      - /c/Users/java/mysql/pls:/var/lib/mysql
      - /c/Users/java/C2S_PROPS/pls:/usr/local/pls
      - /c/Users/java/C2S_PROPS/pls/sql:/usr/local/pls/sql
  pp-ui.c2s.com:
    image: "bhits/pp-ui:0.13.0"
    volumes:
      - /c/Users/java:/java
    mem_limit: 1000m
    links:
      - discovery-server.c2s.com
    restart: always
  admin-ui.c2s.com:
    image: "bhits/admin-portal-ui:0.6.0"
    volumes:
      - /c/Users/java:/java
    mem_limit: 1000m
    links:
      - discovery-server.c2s.com
    restart: always
  dss.c2s.com:
    image: "bhits/dss:1.6.0"
    volumes:
      - /c/Users/java:/java
    entrypoint: ["java","-Xms256m","-Xmx512m","-XX:PermSize=64m","-XX:MaxPermSize=128m","-Xss1m","-jar","/dss.jar","--spring.profiles.active=docker"]
    mem_limit: 1500m
    environment:
      spring.config.location: "file:/java/C2S_PROPS/dss/"
    links:
      - discovery-server.c2s.com
      - guvnor.c2s.com
      - document-validator.c2s.com
    restart: always
  try-policy.c2s.com:
    image: "bhits/try-policy:1.7.0"
    volumes:
      - /c/Users/java:/java
    entrypoint: ["java","-Xms128m","-Xmx256m","-XX:PermSize=32m","-XX:MaxPermSize=64m","-Xss1m","-jar","/tryPolicy.jar","--spring.profiles.active=docker"]
    mem_limit: 1000m
    links:
      - discovery-server.c2s.com
    restart: always
  phr.c2s.com:
    image: "bhits/phr:1.11.0"
    volumes:
      - /c/Users/java:/java
    environment:
      spring.config.location: "file:/java/C2S_PROPS/phr/"
      logging.level.org.springframework.security: "debug"
    entrypoint: ["java","-Xms256m","-Xmx512m","-XX:PermSize=64m","-XX:MaxPermSize=128m","-Xss1m","-jar","/phr.jar","--spring.profiles.active=docker"]
    mem_limit: 1500m
    links:
      - phr-db.c2s.com
      - redis.c2s.com
      - discovery-server.c2s.com
      - iexhub.c2s.com
    restart: always
  phr-db.c2s.com:
    image: mysql:5.7
    volumes_from:
      - phr-db-data.c2s.com
    environment:
        MYSQL_ROOT_PASSWORD: admin
        MYSQL_DATABASE: phr
    ports:
      - "3309:3306"
    restart: always
  phr-db-data.c2s.com:
    image: busybox
    volumes:
      - /c/Users/java/mysql/phr:/var/lib/mysql
  redis.c2s.com:
    image: redis
    ports:
      - "6379:6379"
    restart: always
  clamd.c2s.com:
    image: dinkel/clamavd
  iexhub.c2s.com:
    image: "bhits/iexhub:0.2.0"
    ports:
      - "8454:8443"
      - "8000:8000"
    environment:
      CATALINA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000
    mem_limit: 4000m
    volumes:
      - /c/Users/java:/java
      - /c/Users/java/C2S_PROPS/iexhub/test:/usr/local/tomcat/bin/test
      - /c/Users/java/C2S_PROPS/iexhub/temp:/temp
      - /c/Users/java/C2S_PROPS/iexhub/temp/output:/temp/output
      - /c/Users/java/C2S_PROPS/iexhub/results:/results
      - /c/Users/java/C2S_PROPS/iexhub/results/DebugLogs:/results/DebugLogs
    links:
      - openempi.c2s.com
    restart: always
  patient-registration.c2s.com:
    image: "bhits/patient-registration:1.8.0"
    volumes:
      - /c/Users/java:/java
    entrypoint: ["java","-Xms256m","-Xmx512m","-XX:PermSize=64m","-XX:MaxPermSize=128m","-Xss1m","-jar","/patient-registration.jar","--spring.profiles.active=docker"]
    mem_limit: 1500m
    links:
      - discovery-server.c2s.com
      - uaa.c2s.com
      - iexhub.c2s.com
    restart: always
  patient-user-db.c2s.com:
    image: mysql:5.7
    volumes_from:
      - patient-user-data.c2s.com
    environment:
        MYSQL_ROOT_PASSWORD: admin
        MYSQL_DATABASE: patient-user
    ports:
      - "3310:3306"
    restart: always
  patient-user-data.c2s.com:
    image: busybox
    volumes:
      - /c/Users/java/mysql/patient-user:/var/lib/mysql
  patient-user.c2s.com:
    image: "bhits/patient-user:0.6.0"
    volumes:
      - /c/Users/java:/java
    entrypoint: ["java","-Xms256m","-Xmx512m","-XX:PermSize=64m","-XX:MaxPermSize=128m","-Xss1m","-jar","/patient-user.jar","--spring.profiles.active=mysql,docker"]
    mem_limit: 1000m
    environment:
      spring.config.location: "file:/java/C2S_PROPS/patient-user/"
    ports:
      - "8452:8452"
    links:
      - discovery-server.c2s.com
      - patient-user-db.c2s.com
      - uaa.c2s.com
    restart: always
  discovery-server.c2s.com:
    image: "bhits/discovery-server:0.3.0"
    environment:
      spring.config.location: "file:/java/C2S_PROPS/discovery-server/"
      TZ: "US/Eastern"
    volumes:
      - /c/Users/java:/java
    entrypoint: ["java","-Djavax.net.ssl.trustStore=/java/keystore/c2s.keystore","-Djavax.net.ssl.trustStorePassword=changeit","-Xms256m","-Xmx512m","-XX:PermSize=64m","-XX:MaxPermSize=128m","-Xss1m","-jar","/discovery-server.jar","--spring.profiles.active=ssl,docker"]
    mem_limit: 1500m
    ports:
      - "8761:8761"
    restart: always
  edge-server.c2s.com:
    image: "bhits/edge-server:0.4.1-SNAPSHOT"
    volumes:
      - /c/Users/java:/java
    entrypoint: ["java","-Djavax.net.ssl.trustStore=/java/keystore/c2s.keystore","-Djavax.net.ssl.trustStorePassword=changeit","-Xms256m","-Xmx512m","-XX:PermSize=64m","-XX:MaxPermSize=128m","-Xss1m","-jar","/edge-server.jar","--spring.profiles.active=ssl,eureka-ssl,docker"]
    mem_limit: 1500m
    environment:
      spring.config.location: "file:/java/C2S_PROPS/edge-server/"
    ports:
      - "80:80"
      - "443:443"
    links:
      - discovery-server.c2s.com
      - pls.c2s.com
      - openempi.c2s.com
      - guvnor.c2s.com
      - uaa.c2s.com
      - document-validator.c2s.com
      - document-validator-r1.c2s.com
    restart: always
  openempi.c2s.com:
    image: bhits/openempi:2.2.9
    volumes:
      - /c/Users/java:/java
    ports:
      - "8456:8080"
    links:
      - openempi-db
    restart: always
  openempi-db:
    image: bhits/openempi-db:2.2.9
    environment:
      POSTGRES_USER: openempi
      POSTGRES_PASSWORD: openempi
      POSTGRES_DB: openempi
    volumes:
      - /c/Users/java/postgresql:/var/lib/postgresql
    ports:
      - "5432:5432"
    restart: always
  guvnor.c2s.com:
    image: bhits/guvnor:5.5.0
    volumes:
      - /c/Users/java:/java
    ports:
      - "8457:8443"
    restart: always
  document-validator.c2s.com:
    image: bhits/document-validator:0.2.0
    volumes:
      - /c/Users/java:/java
    ports:
      - "8461:8443"
      - "8460:8080"
    restart: always
  document-validator-r1.c2s.com:
    image: bhits/document-validator-r1:latest
    volumes:
      - /c/Users/java:/java
    restart: always
  pep.c2s.com:
    image: bhits/pep:1.0.0
    volumes:
      - /c/Users/java:/java
    entrypoint: ["java","-Xms128m","-Xmx256m","-XX:PermSize=32m","-XX:MaxPermSize=64m","-Xss1m","-jar","/pep.jar","--spring.profiles.active=docker"]
    mem_limit: 1000m
    links:
      - discovery-server.c2s.com
    environment:
      spring.config.location: "file:/java/C2S_PROPS/pep/"
    restart: always
  context-handler.c2s.com:
    image: bhits/context-handler:1.0.0
    volumes:
      - /c/Users/java:/java
    entrypoint: ["java","-Djavax.net.ssl.trustStore=/java/keystore/c2s.keystore","-Djavax.net.ssl.trustStorePassword=changeit","-Xms256m","-Xmx512m","-XX:PermSize=64m","-XX:MaxPermSize=128m","-Xss1m","-jar","/contextHandler.jar","--spring.profiles.active=docker"]
    mem_limit: 1000m
    links:
      - discovery-server.c2s.com
      - pcm-db.c2s.com
    environment:
      spring.config.location: "file:/java/C2S_PROPS/context-handler/"
    restart: always
