# This is a sample ELK Stack infrastructure setup for the QA environment.
# Please consult to an ELK Stack expert for production grade security and configuration.
version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    mem_limit: 4000m
    restart: always
  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.0
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
# kibana port may not be needed to be exposed if routed via a reverse proxy
#    ports:
#      - "5601:5601"
    mem_limit: 2000m
    restart: always
  logstash:
    image: docker.elastic.co/logstash/logstash:5.6.0
# logstash input port may not be needed to be exposed if it is accessible by log forwarders via Docker networking
#    ports:
#      - "5000:5000"
    mem_limit: 2000m
    restart: always
    command: -e 'input { tcp { port => 5000 codec => "json" } } output { elasticsearch { hosts => ["elasticsearch"] user => "elastic" password => "changeme"} }'
  admin-gateway.c2s.com:
    image: bhits/admin-gateway:${ADMIN_GATEWAY_VERSION}
    ports:
      - "8472:8472"
    mem_limit: 2000m
    restart: always
    environment:
      - security.user.password=${C2S_SYSTEM_ADMIN_PASSWORD}
      - JAVA_OPTS=-Xms512m -Xmx700m -Xss1m
      - TZ="US/Eastern"