# This is a sample ELK Stack infrastructure setup for the development environment.
# Please consult to an ELK Stack expert for production grade security and configuration.
version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.0
# kibana port may not be needed to be exposed if routed via a reverse proxy
    ports:
      - "5601:5601"
  logstash:
    image: docker.elastic.co/logstash/logstash:5.6.0
# logstash input port may not be needed to be exposed if it is accessible by log forwarders via Docker networking
    ports:
      - "5000:5000"
    command: -e 'input { tcp { port => 5000 codec => "json" } } output { elasticsearch { hosts => ["elasticsearch"] user => "elastic" password => "changeme"} }'