version: '2'
services:
  c2s-ui.c2s.com:
    image: bhits/c2s-ui:0.1.0
    volumes:
      - ${C2S_BASE_PATH}/java/C2S_LOGS/c2s-ui:/java/C2S_LOGS/c2s-ui
    restart: always

  c2s-ui-api.c2s.com:
    image: bhits/c2s-ui-api:0.1.0
    volumes:
      - ${C2S_BASE_PATH}/java/C2S_LOGS/c2s-ui-api:/java/C2S_LOGS/c2s-ui-api
    restart: always

  config-server.c2s.com:
    image: bhits/config-server:0.3.0
    volumes:
      - ${C2S_BASE_PATH}/java/C2S_LOGS/config-server:/java/C2S_LOGS/config-server
      - ${C2S_BASE_PATH}/java/c2s-config-data:/java/c2s-config-data
    restart: always

  discovery-server.c2s.com:
    image: bhits/discovery-server:0.11.0
    volumes:
      - ${C2S_BASE_PATH}/java/C2S_LOGS/discovery-server:/java/C2S_LOGS/discovery-server
    restart: always

  edge-server.c2s.com:
    image: bhits/edge-server:0.15.0
    volumes:
      - ${C2S_BASE_PATH}/java/C2S_LOGS/edge-server:/java/C2S_LOGS/edge-server
    ports:
      - "80:80"
      - "443:443"
    restart: always

  pcm.c2s.com:
    image: bhits/pcm:2.0.0
    volumes:
      - ${C2S_BASE_PATH}/java/C2S_LOGS/pcm:/java/C2S_LOGS/pcm
    environment:
      TZ: "US/Eastern"
    restart: always

  pls.c2s.com:
    image: bhits/pls:3.0.0
    volumes:
      - ${C2S_BASE_PATH}/java/C2S_LOGS/pls:/java/C2S_LOGS/pls
    restart: always

  uaa.c2s.com:
    image: bhits/uaa:3.4.1-04
    volumes:
      - ${C2S_BASE_PATH}/java/C2S_LOGS/uaa:/java/C2S_LOGS/uaa
      - ${C2S_BASE_PATH}/java/C2S_PROPS/uaa/uaa.yml:/java/C2S_PROPS/uaa/uaa.yml
    environment:
      JAVA_OPTS: -Xms512m -Xmx700m -Xss1m
      UAA_DB_PASSSWORD: ${UAA_DB_PASSWORD}
      C2S_APP_HOST: ${C2S_APP_HOST}
      C2S_APP_PORT: 80
      UAA_SMTP_HOST: ${UAA_SMTP_HOST}
      UAA_SMTP_PORT: ${UAA_SMTP_PORT}
      UAA_SMTP_USER: ${UAA_SMTP_USER}
      UAA_SMTP_PASSWORD: ${UAA_SMTP_PASSWORD}
    restart: always

  vss.c2s.com:
    image: bhits/vss:0.2.0
    volumes:
      - ${C2S_BASE_PATH}/java/C2S_LOGS/vss:/java/C2S_LOGS/vss
    environment:
      TZ: "US/Eastern"
    restart: always

# Database setup
  pcm-db.c2s.com:
    image: mysql:5.7
    volumes_from:
      - pcm-db-data.c2s.com
    environment:
        MYSQL_ROOT_PASSWORD: ${PCM_DB_PASSWORD}
        MYSQL_DATABASE: pcm
    volumes:
      - ${C2S_BASE_PATH}/java/C2S_PROPS/pcm:/java/C2S_PROPS/pcm
    restart: always

  pcm-db-data.c2s.com:
    image: busybox
    volumes:
      - ${C2S_BASE_PATH}/java/mysql/pcm:/var/lib/mysql

  pls-db.c2s.com:
    image: mysql:5.7
    volumes_from:
      - pls-db-data.c2s.com
    environment:
        MYSQL_ROOT_PASSWORD: ${PLS_DB_PASSWORD}
        MYSQL_DATABASE: pls
    volumes:
      - ${C2S_BASE_PATH}/java/C2S_PROPS/pls:/java/C2S_PROPS/pls
    restart: always

  pls-db-data.c2s.com:
    image: busybox
    volumes:
      - ${C2S_BASE_PATH}/java/mysql/pls:/var/lib/mysql

  uaa-db.c2s.com:
    image: mysql:5.7
    volumes_from:
      - uaa-db-data.c2s.com
    environment:
        MYSQL_ROOT_PASSWORD: ${UAA_DB_PASSWORD}
        MYSQL_DATABASE: uaa
    restart: always

  uaa-db-data.c2s.com:
    image: busybox
    volumes:
      - ${C2S_BASE_PATH}/java/mysql/uaa:/var/lib/mysql

  vss-db.c2s.com:
    image: mysql:5.7
    volumes_from:
      - vss-db-data.c2s.com
    environment:
        MYSQL_ROOT_PASSWORD: ${VSS_DB_PASSWORD}
        MYSQL_DATABASE: vss
    volumes:
      - ${C2S_BASE_PATH}/java/C2S_PROPS/vss:/java/C2S_PROPS/vss
    restart: always

  vss-db-data.c2s.com:
    image: busybox
    volumes:
      - ${C2S_BASE_PATH}/java/mysql/vss:/var/lib/mysql