version: '2'
services:
  c2s-ui.c2s.com:
    image: bhitsdev/c2s-ui:${C2S_UI_VERSION}
    volumes:
      - ${C2S_BASE_PATH}/java/C2S_LOGS/c2s-ui:/java/C2S_LOGS/c2s-ui
    environment:
      JAVA_OPTS: -Xms512m -Xmx700m -Xss1m
      TZ: "US/Eastern"
    mem_limit: 1000m
    restart: always

  c2s-ui-api.c2s.com:
    image: bhitsdev/c2s-ui-api:${C2S_UI_API_VERSION}
    volumes:
      - ${C2S_BASE_PATH}/java/C2S_LOGS/c2s-ui-api:/java/C2S_LOGS/c2s-ui-api
    mem_limit: 1000m
    environment:
      JAVA_OPTS: -Xms512m -Xmx700m -Xss1m
      TZ: "US/Eastern"
    restart: always

  config-server.c2s.com:
    image: bhits/config-server:${CONFIG_SERVER_VERSION}
    volumes:
      - ${C2S_BASE_PATH}/java/C2S_LOGS/config-server:/java/C2S_LOGS/config-server
      - ${C2S_BASE_PATH}/java/C2S_PROPS/c2s-config-data-private:/java/c2s-config-data-private
    mem_limit: 1000m
    environment:
      JAVA_OPTS: -Xms512m -Xmx700m -Xss1m
      TZ: "US/Eastern"
      spring.cloud.config.server.git.uri: file:/java/c2s-config-data-private
      security.user.name: ${BASIC_AUTH_USER}
      security.user.password: ${BASIC_AUTH_PASSWORD}
    restart: always

  context-handler.c2s.com:
    image: bhitsdev/context-handler:${CONTEXT_HANDLER_VERSION}
    volumes:
      - ${C2S_BASE_PATH}/java/C2S_LOGS/context-handler:/java/C2S_LOGS/context-handler
    mem_limit: 1000m
    environment:
      JAVA_OPTS: -Xms512m -Xmx700m -Xss1m
      TZ: "US/Eastern"
      encrypt.key: ${CONFIG_DATA_ENCRYPT_KEY}
    command: --spring.profiles.active=${ENV_APP_PROFILE}
    restart: always

  discovery-server.c2s.com:
    image: bhits/discovery-server:${DISCOVERY_SERVER_VERSION}
    environment:
      JAVA_OPTS: -Xms512m -Xmx700m -Xss1m
      TZ: "US/Eastern"
    volumes:
      - ${C2S_BASE_PATH}/java/C2S_LOGS/discovery-server:/java/C2S_LOGS/discovery-server
    mem_limit: 1500m
    restart: always

  document-validator.c2s.com:
    image: bhitsdev/document-validator:${DOCUMENT_VALIDATOR_VERSION}
    volumes:
      - ${C2S_BASE_PATH}/java/C2S_LOGS/document-validator:/java/C2S_LOGS/document-validator
    environment:
      JAVA_OPTS: -Xms512m -Xmx700m -Xss1m
      TZ: "US/Eastern"
      CATALINA_OPTS: -Dspring.profiles.active=docker
    mem_limit: 1500m
    restart: always

  dss.c2s.com:
    image: bhitsdev/dss:${DSS_VERSION}
    volumes:
      - ${C2S_BASE_PATH}/java/C2S_LOGS/dss:/java/C2S_LOGS/dss
    mem_limit: 1500m
    environment:
      JAVA_OPTS: -Xms512m -Xmx700m -Xss1m
      TZ: "US/Eastern"
      encrypt.key: ${CONFIG_DATA_ENCRYPT_KEY}
    command: --spring.profiles.active=${ENV_APP_PROFILE}
    restart: always

  edge-server.c2s.com:
    image: bhitsdev/edge-server:${EDGE_SERVER_VERSION}
    volumes:
      - ${C2S_BASE_PATH}/java/C2S_LOGS/edge-server:/java/C2S_LOGS/edge-server
      - ${C2S_BASE_PATH}/java/keystore/edge-server.keystore:/java/keystore/edge-server.keystore
    mem_limit: 1500m
    environment:
      JAVA_OPTS: -Xms512m -Xmx700m -Xss1m
      TZ: "US/Eastern"
      encrypt.key: ${CONFIG_DATA_ENCRYPT_KEY}
    command: --spring.profiles.active=${ENV_APP_PROFILE}
    ports:
      - "80:80"
    restart: always

  guvnor.c2s.com:
    image: bhits/guvnor:${GUVNOR_VERSION}
    volumes:
      - ${C2S_BASE_PATH}/java/C2S_LOGS/guvnor:/java/C2S_LOGS/guvnor
    environment:
      CATALINA_OPTS: -Xms512m -Xmx700m -Xss1m
      TZ: "US/Eastern"
    mem_limit: 1000m
    restart: always

  hapi-fhir.c2s.com:
    image: bhits/hapi-fhir-jpaserver:2.3-01
    environment:
      TZ: "US/Eastern"
      CATALINA_OPTS: -Djdbc.url=jdbc:mysql://hapi-fhir-db.c2s.com:3306/hapi-fhir?autoReconnect=true -Djdbc.password=${HAPI_FHIR_DB_PASSWORD} -Xms512m -Xmx1024m -Xss1m
    ports:
      - "80:8080"
    mem_limit: 1024m
    restart: always

  iexhub-pix-pdq.c2s.com:
    image: bhitsdev/iexhub-pix-pdq:${IEXHUB_PIX_PDQ_VERSION}
    volumes:
      - ${C2S_BASE_PATH}/java/C2S_LOGS/iexhub-pix-pdq:/java/C2S_LOGS/iexhub-pix-pdq
    mem_limit: 1000m
    environment:
      JAVA_OPTS: -Xms512m -Xmx700m -Xss1m
      TZ: "US/Eastern"
      encrypt.key: ${CONFIG_DATA_ENCRYPT_KEY}
    command: --spring.profiles.active=${ENV_APP_PROFILE}
    restart: always

  iexhub-xdsb.c2s.com:
    image: bhitsdev/iexhub-xdsb:${IEXHUB_XDSB_VERSION}
    volumes:
      - ${C2S_BASE_PATH}/java/C2S_LOGS/iexhub-xdsb:/java/C2S_LOGS/iexhub-xdsb
    mem_limit: 1000m
    environment:
      JAVA_OPTS: -Xms512m -Xmx700m -Xss1m
      TZ: "US/Eastern"
      encrypt.key: ${CONFIG_DATA_ENCRYPT_KEY}
    command: --spring.profiles.active=${ENV_APP_PROFILE}
    restart: always

  master-ui.c2s.com:
    image: bhitsdev/master-ui:${MASTER_UI_VERSION}
    volumes:
      - ${C2S_BASE_PATH}/java/C2S_LOGS/master-ui:/java/C2S_LOGS/master-ui
    environment:
      JAVA_OPTS: -Xms512m -Xmx700m -Xss1m
      TZ: "US/Eastern"
    mem_limit: 1000m
    restart: always

  master-ui-api.c2s.com:
    image: bhitsdev/master-ui-api:${MASTER_UI_API_VERSION}
    volumes:
      - ${C2S_BASE_PATH}/java/C2S_LOGS/master-ui-api:/java/C2S_LOGS/master-ui-api
    mem_limit: 1000m
    environment:
      JAVA_OPTS: -Xms512m -Xmx700m -Xss1m
      TZ: "US/Eastern"
      encrypt.key: ${CONFIG_DATA_ENCRYPT_KEY}
    command: --spring.profiles.active=${ENV_APP_PROFILE}
    restart: always

  pcm.c2s.com:
    image: bhitsdev/pcm:${PCM_VERSION}
    volumes:
      - ${C2S_BASE_PATH}/java/C2S_LOGS/pcm:/java/C2S_LOGS/pcm
    environment:
      TZ: "US/Eastern"
      JAVA_OPTS: -Xms512m -Xmx700m -Xss1m
      encrypt.key: ${CONFIG_DATA_ENCRYPT_KEY}
    command: --spring.profiles.active=${ENV_APP_PROFILE}
    mem_limit: 2000m
    restart: always

  pep.c2s.com:
    image: bhitsdev/pep:${PEP_VERSION}
    volumes:
      - ${C2S_BASE_PATH}/java/C2S_LOGS/pep:/java/C2S_LOGS/pep
    mem_limit: 1000m
    environment:
      TZ: "US/Eastern"
      JAVA_OPTS: -Xms512m -Xmx700m -Xss1m
      encrypt.key: ${CONFIG_DATA_ENCRYPT_KEY}
    command: --spring.profiles.active=${ENV_APP_PROFILE}
    restart: always

  pep-api.c2s.com:
    image: bhitsdev/pep-api:${PEP_API_VERSION}
    volumes:
      - ${C2S_BASE_PATH}/java/C2S_LOGS/pep-api:/java/C2S_LOGS/pep-api
    mem_limit: 1000m
    environment:
      TZ: "US/Eastern"
      JAVA_OPTS: -Xms512m -Xmx700m -Xss1m
      encrypt.key: ${CONFIG_DATA_ENCRYPT_KEY}
    command: --spring.profiles.active=${ENV_APP_PROFILE}
    restart: always

  phr.c2s.com:
    image: bhitsdev/phr:${PHR_VERSION}
    volumes:
      - ${C2S_BASE_PATH}/java/C2S_LOGS/phr:/java/C2S_LOGS/phr
    mem_limit: 1500m
    environment:
      JAVA_OPTS: -Xms512m -Xmx700m -Xss1m
      TZ: "US/Eastern"
      encrypt.key: ${CONFIG_DATA_ENCRYPT_KEY}
    command: --spring.profiles.active=${ENV_APP_PROFILE}
    restart: always

  pls.c2s.com:
    image: bhitsdev/pls:${PLS_VERSION}
    environment:
      CATALINA_OPTS: -Xms512m -Xmx2000m -Xss1m
      encrypt.key: ${CONFIG_DATA_ENCRYPT_KEY}
      TZ: "US/Eastern"
    command: --spring.profiles.active=${ENV_APP_PROFILE}
    mem_limit: 2000m
    volumes:
      - ${C2S_BASE_PATH}/java/C2S_LOGS/pls:/java/C2S_LOGS/pls
    restart: always

  provider-ui.c2s.com:
     image: bhitsdev/provider-ui:${PROVIDER_UI_VERSION}
     volumes:
      - ${C2S_BASE_PATH}/java/C2S_LOGS/provider-ui:/java/C2S_LOGS/provider-ui
     environment:
       JAVA_OPTS: -Xms512m -Xmx700m -Xss1m
       TZ: "US/Eastern"
     mem_limit: 1000m
     restart: always

  provider-ui-api.c2s.com:
     image: bhitsdev/provider-ui-api:${PROVIDER_UI_API_VERSION}
     volumes:
       - ${C2S_BASE_PATH}/java/C2S_LOGS/provider-ui-api:/java/C2S_LOGS/provider-ui-api
     mem_limit: 1000m
     environment:
       JAVA_OPTS: -Xms512m -Xmx700m -Xss1m
       TZ: "US/Eastern"
     restart: always

  staff-ui.c2s.com:
    image: bhitsdev/staff-ui:${STAFF_UI_VERSION}
    volumes:
      - ${C2S_BASE_PATH}/java/C2S_LOGS/staff-ui:/java/C2S_LOGS/staff-ui
    environment:
      JAVA_OPTS: -Xms512m -Xmx700m -Xss1m
      TZ: "US/Eastern"
    mem_limit: 1000m
    restart: always

  staff-ui-api.c2s.com:
    image: bhitsdev/staff-ui-api:${STAFF_UI_API_VERSION}
    volumes:
      - ${C2S_BASE_PATH}/java/C2S_LOGS/staff-ui-api:/java/C2S_LOGS/staff-ui-api
    mem_limit: 1000m
    environment:
      JAVA_OPTS: -Xms512m -Xmx700m -Xss1m
      TZ: "US/Eastern"
    restart: always

  try-policy.c2s.com:
    image: bhitsdev/try-policy:${TRY_POLICY_VERSION}
    volumes:
      - ${C2S_BASE_PATH}/java/C2S_LOGS/try-policy:/java/C2S_LOGS/try-policy
    mem_limit: 1500m
    environment:
      JAVA_OPTS: -Xms512m -Xmx700m -Xss1m
      encrypt.key: ${CONFIG_DATA_ENCRYPT_KEY}
      TZ: "US/Eastern"
    command: --spring.profiles.active=${ENV_APP_PROFILE}
    restart: always

  uaa.c2s.com:
    image: bhitsdev/uaa:${UAA_VERSION}
    volumes:
      - ${C2S_BASE_PATH}/java/C2S_LOGS/uaa:/java/C2S_LOGS/uaa
      - ${C2S_BASE_PATH}/java/C2S_PROPS/uaa/uaa.yml:/java/C2S_PROPS/uaa/uaa.yml
    environment:
      JAVA_OPTS: -Xms512m -Xmx700m -Xss1m
      TZ: "US/Eastern"
      UAA_DB_PASSSWORD: ${UAA_DB_PASSWORD}
      C2S_APP_HOST: ${C2S_APP_HOST}
      C2S_APP_PORT: 80
      C2S_DB_HOST: ${C2S_DB_HOST}
      C2S_DB_PORT: 3306
      UAA_SMTP_HOST: ${UAA_SMTP_HOST}
      UAA_SMTP_PORT: ${UAA_SMTP_PORT}
      UAA_SMTP_USER: ${UAA_SMTP_USER}
      UAA_SMTP_PASSWORD: ${UAA_SMTP_PASSWORD}
    mem_limit: 1500m
    restart: always

  ums.c2s.com:
    image: bhitsdev/ums:${UMS_VERSION}
    volumes:
      - ${C2S_BASE_PATH}/java/C2S_LOGS/ums:/java/C2S_LOGS/ums
      - ${C2S_BASE_PATH}/java/C2S_PROPS/ums:/java/C2S_PROPS/ums
    environment:
      TZ: "US/Eastern"
      JAVA_OPTS: -Xms512m -Xmx700m -Xss1m
      encrypt.key: ${CONFIG_DATA_ENCRYPT_KEY}
    command: --spring.profiles.active=${ENV_APP_PROFILE}
    mem_limit: 2000m
    restart: always

  vss.c2s.com:
    image: bhitsdev/vss:${VSS_VERSION}
    volumes:
      - ${C2S_BASE_PATH}/java/C2S_LOGS/vss:/java/C2S_LOGS/vss
    environment:
      TZ: "US/Eastern"
      JAVA_OPTS: -Xms512m -Xmx700m -Xss1m
      encrypt.key: ${CONFIG_DATA_ENCRYPT_KEY}
    command: --spring.profiles.active=${ENV_APP_PROFILE}
    mem_limit: 2000m
    restart: always